language: python
sudo: false
python:
    - "3.6"

dist: xenial
services:
    - xvfb
install:
    # Install requirements
    - bash install.sh
    - . $HOME/miniconda/etc/profile.d/conda.sh
    - conda activate getint
    - conda list
    - which gcc
script:
    - export PYTHONPATH="."
    - py.test --cov=.
    - echo `sphinx-build --version`
after_success:
    - pip install codecov codacy-coverage
    - codecov
    - coverage xml
    - python-codacy-coverage -r coverage.xml
    - bash <(curl -s https://codecov.io/bash)
